workflows:
  ios-native-build:
    name: iOS Native Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iOS
          xcodegen generate
      - name: Build iOS App
        script: |
          cd iOS
          # Find the first available iOS Simulator ID from the list provided by the environment
          SIM_ID=$(xcrun xctrace list devices | grep "Simulator" | grep -v "Apple Watch" | grep -v "Apple TV" | head -n 1 | awk '{print $NF}' | tr -d '()')
          echo "Selected Simulator ID: $SIM_ID"
          
          # Build using the dynamic ID
          xcodebuild build \
            -project TicketingSystem.xcodeproj \
            -scheme TicketingSystem \
            -sdk iphonesimulator \
            -destination "id=$SIM_ID" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
    artifacts:
      - iOS/build/Release-iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
