workflows:
  ios-native-build:
    name: iOS Native Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iOS
          xcodegen generate
      - name: Build iOS App
        script: |
          cd iOS
          # Debug: List available destinations to the log
          xcodebuild -project TicketingSystem.xcodeproj -scheme TicketingSystem -showdestinations
          
          # Build using a generic simulator destination
          # This is the most compatible way to build for "any" simulator
          xcodebuild build \
            -project TicketingSystem.xcodeproj \
            -scheme TicketingSystem \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CONFIGURATION_BUILD_DIR=build

    artifacts:
      - iOS/build/*.app
      - /tmp/xcodebuild_logs/*.log
