workflows:
  ios-native-build:
    name: iOS Native Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iOS
          xcodegen generate
      - name: Build iOS App
        script: |
          cd iOS
          # Build for Simulator to bypass code signing requirements (since we don't have certs).
          # This verifies the code compiles and produces an .app capable of running in a simulator.
          xcodebuild build -project TicketingSystem.xcodeproj -scheme TicketingSystem -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' CODE_SIGNING_ALLOWED=NO
    artifacts:
      - iOS/build/Release-iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
