workflows:
  ios-native-build:
    name: iOS Native Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iOS
          xcodegen generate
      - name: Build iOS App
        script: |
          cd iOS
          # Build the app using xcodebuild. 
          # We disable code signing for now to ensure it builds without certificates.
          xcodebuild build -project TicketingSystem.xcodeproj -scheme TicketingSystem -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
    artifacts:
      - iOS/build/Release-iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
