workflows:
  ios-native-build:
    name: iOS Native Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iOS
          xcodegen generate
      - name: Build iOS App
        script: |
          cd iOS
          # Build using the generic simulator destination.
          # ONLY_ACTIVE_ARCH=YES ensures it only builds for the architecture of the build machine (arm64 for M2).
          xcodebuild clean build \
            -project TicketingSystem.xcodeproj \
            -scheme TicketingSystem \
            -destination "generic/platform=iOS Simulator" \
            -configuration Debug \
            ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CONFIGURATION_BUILD_DIR=build



    artifacts:
      - iOS/build/*.app
      - /tmp/xcodebuild_logs/*.log
