workflows:
  ios-native-build:
    name: iOS Native Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          cd iOS
          xcodegen generate
      - name: Build iOS App
        script: |
          cd iOS
          # Try building with the generic placeholder first
          if ! xcodebuild build -project TicketingSystem.xcodeproj -scheme TicketingSystem -sdk iphonesimulator -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO; then
            echo "Generic destination failed, trying to find a specific simulator ID..."
            # Dynamic fallback: find the first available simulator ID from xctrace
            SIM_ID=$(xcrun xctrace list devices | grep "Simulator" | grep -vE "Watch|TV" | head -n 1 | awk -F '[()]' '{print $(NF-1)}')
            echo "Attempting build with ID: $SIM_ID"
            xcodebuild build -project TicketingSystem.xcodeproj -scheme TicketingSystem -sdk iphonesimulator -destination "id=$SIM_ID" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          fi
    artifacts:
      - iOS/build/Release-iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
