name: TicketingSystem
options:
  bundleIdPrefix: com.ticketing
  deploymentTarget:
    iOS: 16.0
targets:
  TicketingSystem:
    type: application
    platform: iOS
    sources:
      - path: TicketingSystem
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ticketing.warehouse
        Marketing_Version: 1.0.0
        CODE_SIGNING_REQUIRED: NO
        INFOPLIST_FILE: TicketingSystem/Info.plist
schemes:
  TicketingSystem:
    build:
      targets:
        TicketingSystem: all
    run:
      executable: TicketingSystem

